In [22]:
from math import sqrt
from scipy import signal
import numpy as np

def compute_gradient(image):
    filter1 = np.array([[-1, 0, 1], [-2, 0, 2], [-1, 0, 1]])
    filter2 = np.array([[1,2,1], [0,0,0], [-1,-2,-1]])
    Gx = signal.convolve2d(image, filter1)
    Gy = signal.convolve2d(image, filter2)
    im_magnitude = np.sqrt(Gx**2+Gy**2)
    im_direction = (np.tan(Gx/Gy))**(-1)                   
    return Gx, Gy, im_magnitude,im_direction

In [23]:
import cv2
img = cv2.imread('./images/image2.jpg')
print(img.shape)
img = np.mean(img, axis=2)
print(img.shape)

(533, 800, 3)
(533, 800)


In [24]:
compute_gradient(img)

<ipython-input-22-18d1f5be395c>:11: RuntimeWarning: divide by zero encountered in true_divide
  im_direction = (np.tan(Gx/Gy))**(-1)
<ipython-input-22-18d1f5be395c>:11: RuntimeWarning: invalid value encountered in true_divide
  im_direction = (np.tan(Gx/Gy))**(-1)
<ipython-input-22-18d1f5be395c>:11: RuntimeWarning: invalid value encountered in tan
  im_direction = (np.tan(Gx/Gy))**(-1)
<ipython-input-22-18d1f5be395c>:11: RuntimeWarning: divide by zero encountered in reciprocal
  im_direction = (np.tan(Gx/Gy))**(-1)


(array([[-203., -208.,   -4., ...,    0.,  236.,  236.],
        [-609., -620.,   -8., ...,    0.,  708.,  708.],
        [-813., -816.,    0., ...,    0.,  944.,  944.],
        ...,
        [-513., -506.,   47., ...,   15.,  877.,  869.],
        [-463., -454.,   69., ...,   14.,  655.,  649.],
        [-170., -166.,   31., ...,    5.,  218.,  216.]]),
 array([[ 203.,  614.,  826., ...,  944.,  708.,  236.],
        [ 203.,  610.,  814., ...,  944.,  708.,  236.],
        [   1.,   -6.,  -22., ...,    0.,    0.,    0.],
        ...,
        [  73.,  216.,  257., ...,   -9.,   -9.,   -3.],
        [-123., -368., -483., ..., -876., -653., -217.],
        [-170., -506., -641., ..., -873., -650., -216.]]),
 array([[ 287.08535316,  648.27463316,  826.00968517, ...,  944.        ,
          746.2975278 ,  333.75440072],
        [ 641.94236501,  869.77008456,  814.03931109, ...,  944.        ,
         1001.26320216,  746.2975278 ],
        [ 813.00061501,  816.02205853,   22.        , ...,